config/routes.rb
Mutations::Application.routes.draw do

  resources :posts

  resources :dominances

  resources :chromosomes

  resources :zygosities

  resources :genders

  resources :causalities

  resources :age_of_onsets

  resources :curabilities

  resources :ethnic_groups

  devise_for :users, :path_prefix => 'my'
  resources :users

  resources :genes do
    collection do
      get 'report'
    end

  end
  resources :ncbi_pubmed_articles
  resources :roles
  mount Resque::Server.new, :at => "/resque", :as => 'resque'
  resources :portals do
    collection do
      get 'science'
      get 'medical'
    end
  end

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable :rememberable, :registerable
  devise :database_authenticatable, :recoverable, :trackable, :validatable
  acts_as_tagger
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :login, :firstname, :lastname, :active


  belongs_to :role
  has_many :posts, :dependent => :destroy
  before_create :set_default_role

  validates_presence_of :login, :email, :firstname, :lastname
  validates_uniqueness_of :login, :email


  def active_for_authentication?
    super && active?
  end

  def inactive_message
    if !active
      :not_active
    else
      super # Use whatever other message
    end
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.active?
      recoverable.errors[:base] << I18n.t("devise.failure.not_active")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end



  private
  def set_default_role
    if self.role.nil?
      self.role = Role.find_by_name('user')
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  authorize_resource

  def index
    if admin?
      @users = User.order("login ASC")
    else
      @users = User.where(id: current_user.id)
    end


    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @users }
    end
  end
  
  # GET /:users/1
    # GET /:users/1.json
    def show
      if admin? || params[:id] == current_user.id
        @user = User.find(params[:id])
      else
        @user = User.find(current_user.id)
      end


      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end
  
    # GET /:users/new
    # GET /:users/new.json
    def new
      @user = User.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    end
  
    # GET /:users/1/edit
    def edit
      if admin? || params[:id] == current_user.id
        @user = User.find(params[:id])
      else
        @user = User.find(current_user.id)
      end

    end
  
    # POST /:users
    # POST /:users.json
  def create
    @user = User.new
    @user.accessible = [:role_id] if admin?
    @user.attributes = params[:user]

    respond_to do |format|
      if admin?
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { redirect_to new_user_path }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        redirect_to genes_path, error: "You are not authorized to create new users"
      end

    end
  end
  
    # PUT /:users/1
    # PUT /:users/1.json
    def update
      @user = User.find(params[:id])
      @user.accessible = [:role_id] if admin?

      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end

      respond_to do |format|
        if admin? || @user.id == current_user.id
          if @user.update_attributes(params[:user])
            format.html { redirect_to @user, notice: 'User was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        else
          redirect_to genes_path, error: "You are not authorized to update this user!."
        end
      end
    end
  
    # DELETE /:users/1
    # DELETE /:users/1.json
    def destroy
      @user = User.find(params[:id])
      if admin?
        @user.destroy
      else
        redirect_to genes_path, error: "You are not authorized to delete this user!"
      end

  
      respond_to do |format|
        format.html { redirect_to :users }
        format.json { head :no_content }
      end
    end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|

  = f.input :login, class: "text_field"
  = f.input :firstname, class: "text_field"
  = f.input :lastname , class: "text_field"
  = f.input :email, class: "email_field"
  -if params[:action] == "edit" && admin?
    = f.association :role, :as => :radio_buttons
  -if admin?
    = f.input :active
  = f.input :password, class: "password_field"
  = f.input :password_confirmation, class: "password_field"

  -if params[:action] == "edit"
    %p
      = "The current role assigned to this user is"
      %strong
        = @user.role.name
        = "."
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      users_path, :class => 'btn'                                  |

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, |
      :default => "Edit #{model_class.model_name.human}")                                      |
= render :partial => 'form'

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize
-if user_signed_in?
  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:id)
        %th= model_class.human_attribute_name(:login)
        %th= model_class.human_attribute_name(:firstname)
        %th= model_class.human_attribute_name(:lastname)
        %th= model_class.human_attribute_name(:email)
        %th= model_class.human_attribute_name(:created_at)
        %th= Role
        %th Status
        %th= t '.actions', :default => t("helpers.actions")
    %tbody
      - @users.each do |user|
        %tr
          %td= user.id
          %td= link_to user.login, user_path(user)
          %td= user.firstname
          %td= user.lastname
          %td= user.email
          %td= user.created_at.strftime("%Y-%m-%d")
          %td= user.role.name
          %td=raw user.active ? "<span class='green'>active</span>":"<span class='red'>inactive</span>"

          %td
            -if can? :update, User
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
              -if can? :destroy, User
                = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
  -if can? :create, User
    = link_to t('.new', :default => t("helpers.links.new")),new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, |
      :default => "New #{model_class.model_name.human}")                                      |
= render :partial => 'form'

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1
    = t '.title', :default => model_class.model_name.human
    = @user.login
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:login)
      \:
  %dd= @user.login
  %dt
    %strong
      = model_class.human_attribute_name(:firstname)
      \:
  %dd= @user.firstname
  %dt
    %strong
      = model_class.human_attribute_name(:lastname)
      \:
    %dd= @user.lastname
  %dt
    %strong
      = model_class.human_attribute_name(:email)
      \:
    %dd= mail_to @user.email, @user.email
  %dt
    %strong
      Role
      \:
    %dd= @user.role.name
  %dt
    %strong
      Status
      \:
    %dd= @user.active ? "active":"inactive"
  %dt
    %strong
      = model_class.human_attribute_name(:created_at)
      \:
    %dd= @user.created_at.strftime("%Y-%m-%d")
  %dt
    %strong
      = model_class.human_attribute_name(:updated_at)
      \:
    %dd= @user.updated_at.strftime("%Y-%m-%d")
  - unless @user.last_sign_in_at == nil
    %dt
      %strong
        = model_class.human_attribute_name(:last_sign_in_at)
        \:
      %dd= @user.last_sign_in_at.strftime("%Y-%m-%d")


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    users_path, :class => 'btn'                              |
  -#
  -if admin? || @user.id == current_user.id
    = link_to t('.edit', :default => t("helpers.links.edit")), |
      edit_user_path(@user), :class => 'btn'                   |
  -#
  -if admin?
    = link_to t('.destroy', :default => t("helpers.links.destroy")),                                  |
      user_path(@user),                                                                               |
      :method => 'delete',                                                                            |
      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), |
      :class => 'btn btn-danger'                                                                      |