config/routes.rb
Mutations::Application.routes.draw do

  resources :posts

  resources :dominances

  resources :chromosomes

  resources :zygosities

  resources :genders

  resources :causalities

  resources :age_of_onsets

  resources :curabilities

  resources :ethnic_groups

  devise_for :users, :path_prefix => 'my'
  resources :users

  resources :genes do
    collection do
      get 'report'
    end

  end
  resources :ncbi_pubmed_articles
  resources :roles
  mount Resque::Server.new, :at => "/resque", :as => 'resque'
  resources :portals do
    collection do
      get 'science'
      get 'medical'
    end
  end

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_authorization_check
  def index


    @unclassified_genes = Gene.without_classification
    @classified_genes = Gene.with_classification
    @common_genes = Gene.common_in_sa
    @progress = Gene.calculate_progress(@unclassified_genes.size, @classified_genes.size)
    @progress_sa = Gene.calculate_progress(@common_genes.without_classification.size, @common_genes.with_classification.size)
    @posts = Post.published.order("created_at DESC").limit(2) || []
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
-unless user_signed_in?
  %p
    = link_to "Sign in", new_user_session_path
-else
  %h2
    Welcome,
    =current_user.firstname
  %p
    %br
  -if Gene.all.size > 0
    .row
      .span6
        .well.dashboard.top
          %legend
            = image_tag('South-Africa-Flag.png', class: "flag")
            Common in South Africa

            = "(#{@common_genes.length})"
            .progress{:style => "box-shadow: 1px 1px 2px #888;"}
              .bar.bar-success{ :style => 'width:' + @progress_sa["classified"].to_s + '%;'}
                %p
                  = "#{@progress_sa["classified"]}%"
              .bar.bar-danger{ :style => 'width:' + @progress_sa["unclassified"].to_s + '%;'}
                %p
                  = "#{@progress_sa["unclassified"]}%"
          %p
            =image_tag 'true.png'
            = "Common disease genes already classified (#{@common_genes.with_classification.size})"
            %p
            =raw @common_genes.with_classification.collect { |gene| "#{link_to gene.name, edit_gene_path(gene)}" }.join(", ")

          %p
            =image_tag 'false.png'
            = "Common disease genes still not classified (#{@common_genes.without_classification.size})"
            %p.justified
            =raw @common_genes.without_classification.collect { |gene| "#{link_to gene.name, edit_gene_path(gene)}" }.join(", ")


      .span6
        .well.dashboard.top
          %legend
            Classification effort
            .progress{:style => "box-shadow: 1px 1px 2px #888;"}
              .bar.bar-success{ :style => 'width:' + @progress["classified"] + '%;'}
                %p
                  = "#{@progress["classified"]}%"
              .bar.bar-danger{ :style => 'width:' + @progress["unclassified"] + '%;'}
                %p
                  = "#{@progress["unclassified"]}%"
          %p
            =image_tag 'true.png'
            = "Genes already classified (#{@classified_genes.size})"
            %p
            =raw @classified_genes.limit(20).collect { |gene| "#{link_to gene.name, edit_gene_path(gene)}" }.join(", ")
            ="..."
          %p
            =image_tag 'false.png'
            = "Genes still not classified (#{@unclassified_genes.size})"
            %p.justified
            =raw @unclassified_genes.limit(20).collect { |gene| "#{link_to gene.name, edit_gene_path(gene)}" }.join(", ")
            ="..."
          .clear
        .clear

  .row
    -if @posts.length > 0
      -@posts.each do |post|
        .span6
          .well.dashboard.bottom
            %legend
              =link_to post.title, post
            %h6
              = post.created_at.strftime("%Y/%m/%d at %T")
            %p
              = post.content



  %p
    = link_to "all posts", posts_path