config/routes.rb
Mutations::Application.routes.draw do

  resources :posts

  resources :dominances

  resources :chromosomes

  resources :zygosities

  resources :genders

  resources :causalities

  resources :age_of_onsets

  resources :curabilities

  resources :ethnic_groups

  devise_for :users, :path_prefix => 'my'
  resources :users

  resources :genes do
    collection do
      get 'report'
    end

  end
  resources :ncbi_pubmed_articles
  resources :roles
  mount Resque::Server.new, :at => "/resque", :as => 'resque'
  resources :portals do
    collection do
      get 'science'
      get 'medical'
    end
  end

  root :to => 'welcome#index'

end

app/models/age_of_onset.rb
class AgeOfOnset < ActiveRecord::Base
  attr_accessible :value

  has_many :age_onsetizations
  has_many :genes, :through => :age_onsetizations

end

app/controllers/age_of_onsets_controller.rb
class AgeOfOnsetsController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource

  # GET /age_of_onsets
  # GET /age_of_onsets.json
  def index
    @age_of_onsets = AgeOfOnset.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @age_of_onsets }
    end
  end

  # GET /age_of_onsets/1
  # GET /age_of_onsets/1.json
  def show
    @age_of_onset = AgeOfOnset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @age_of_onset }
    end
  end

  # GET /age_of_onsets/new
  # GET /age_of_onsets/new.json
  def new
    @age_of_onset = AgeOfOnset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @age_of_onset }
    end
  end

  # GET /age_of_onsets/1/edit
  def edit
    @age_of_onset = AgeOfOnset.find(params[:id])
  end

  # POST /age_of_onsets
  # POST /age_of_onsets.json
  def create
    @age_of_onset = AgeOfOnset.new(params[:age_of_onset])

    respond_to do |format|
      if @age_of_onset.save
        format.html { redirect_to @age_of_onset, notice: 'Age of onset was successfully created.' }
        format.json { render json: @age_of_onset, status: :created, location: @age_of_onset }
      else
        format.html { render action: "new" }
        format.json { render json: @age_of_onset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /age_of_onsets/1
  # PUT /age_of_onsets/1.json
  def update
    @age_of_onset = AgeOfOnset.find(params[:id])

    respond_to do |format|
      if @age_of_onset.update_attributes(params[:age_of_onset])
        format.html { redirect_to age_of_onsets_path, notice: 'Age of onset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @age_of_onset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /age_of_onsets/1
  # DELETE /age_of_onsets/1.json
  def destroy
    @age_of_onset = AgeOfOnset.find(params[:id])
    @age_of_onset.destroy


    respond_to do |format|
      format.html { redirect_to age_of_onsets_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/age_of_onsets_helper.rb
module AgeOfOnsetsHelper
end

app/views/age_of_onsets/_form.html.haml
= simple_form_for(@age_of_onset) do |f|
  = f.error_notification
  .form-inputs
    = f.input :value
  .form-actions
    = f.button :submit

app/views/age_of_onsets/edit.html.haml
%h1 Editing Age Of Onset
= render 'form'


=link_to 'Back', age_of_onsets_path

app/views/age_of_onsets/index.html.haml
- model_class = AgeOfOnset
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th.left= model_class.human_attribute_name(:value)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @age_of_onsets.each do |age|
      %tr
        %td.left= age.value
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_age_of_onset_path(age), :class => 'btn btn-mini'
          -#
          = link_to t('.destroy', :default => t("helpers.links.destroy")),age_of_onset_path(age), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),:class => 'btn btn-mini btn-danger'
= link_to t('.new', :default => t("helpers.links.new")), new_age_of_onset_path, :class => 'btn btn-primary'

app/views/age_of_onsets/new.html.haml
%h1 New Age Of Onset
= render 'form'
= link_to 'Back', age_of_onsets_path

app/views/age_of_onsets/show.html.haml
%p#notice= notice
.well.well-small
  %b Value:
  = @age_of_onset.value
= link_to 'Edit', edit_age_of_onset_path(@age_of_onset)
|
\#{link_to 'Back', age_of_onsets_path}