config/routes.rb
Mutations::Application.routes.draw do

  resources :posts

  resources :dominances

  resources :chromosomes

  resources :zygosities

  resources :genders

  resources :causalities

  resources :age_of_onsets

  resources :curabilities

  resources :ethnic_groups

  devise_for :users, :path_prefix => 'my'
  resources :users

  resources :genes do
    collection do
      get 'report'
    end

  end
  resources :ncbi_pubmed_articles
  resources :roles
  mount Resque::Server.new, :at => "/resque", :as => 'resque'
  resources :portals do
    collection do
      get 'science'
      get 'medical'
    end
  end

  root :to => 'welcome#index'

end

app/models/gene.rb
class Gene < ActiveRecord::Base
  attr_accessible :disease,:common_in_sa, :chromosome, :covered_bases, :ncbi_result_id, :name, :number_amplicons, :overall_coverage, :total_bases, :ethnic_group_ids, :curability_ids, :age_of_onset_ids, :causality_ids,:comment_tags, :incident_tags, :gender_ids, :zygosity_ids, :chromosome_ids, :dominance_ids
  has_one :ncbi_result, :dependent => :destroy

  has_many :ethnic_groupings
  has_many :ethnic_groups, :through => :ethnic_groupings

  has_many :curabilitizations
  has_many :curabilities, :through => :curabilitizations

  has_many :age_onsetizations
  has_many :age_of_onsets, :through => :age_onsetizations

  has_many :causalitizations
  has_many :causalities, :through => :causalitizations

  has_many :gender_classifications
  has_many :genders, :through => :gender_classifications

  has_many :zygosity_classifications
  has_many :zygosities, :through => :zygosity_classifications

  has_many :chromosome_classifications
  has_many :chromosomes, :through => :chromosome_classifications

  has_many :dominance_classifications
  has_many :dominances, :through => :dominance_classifications

  # scopes
  scope :without_classification, where("id NOT IN (SELECT gene_id FROM ethnic_groupings)").where("id NOT IN (SELECT gene_id FROM curabilitizations)").where("id NOT IN (SELECT gene_id FROM age_onsetizations)").where("id NOT IN (SELECT gene_id FROM gender_classifications)").where("id NOT IN (SELECT gene_id FROM zygosity_classifications)").where("id NOT IN (SELECT gene_id FROM chromosome_classifications)").where("id NOT IN (SELECT gene_id FROM dominance_classifications)")
  scope :with_classification,    where( "id IN (SELECT gene_id FROM ethnic_groupings) OR id IN (SELECT gene_id FROM curabilitizations) OR id IN (SELECT gene_id FROM age_onsetizations) OR id IN (SELECT gene_id FROM gender_classifications) OR id IN (SELECT gene_id FROM zygosity_classifications) OR id IN (SELECT gene_id FROM chromosome_classifications) OR id IN (SELECT gene_id FROM dominance_classifications)")
  scope :common_in_sa,           where(:common_in_sa => true)


  acts_as_taggable
  acts_as_taggable_on :comments, :incidents

  attr_accessor :comment_tags, :incident_tags


  #create virtual attribute for file name
  attr_accessor :mutation_annotation_file


  validates_presence_of :name, :chromosome
  validates_uniqueness_of :name

  define_index do
    indexes :name
    indexes chromosome
    indexes disease

    # add classification records
    indexes curabilities.value, as: :gene_curabilities
    indexes ethnic_groups.value, as: :gene_ethnic_groups
    indexes age_of_onsets.value, as: :gene_age_of_onsets
    indexes causalities.name, as: :gene_causalities
    indexes genders.name, as: :gene_genders
    indexes zygosities.name, as: :gene_zygosities
    indexes chromosomes.name, as: :gene_chromosomes
    indexes dominances.name, as: :gene_dominances

    indexes ncbi_result.official_full_name, as: :result_official_full_name
    indexes ncbi_result.phenotype, as: :result_phenotype
    indexes ncbi_result.summary, as: :result_summary
    #indexes ncbi_result.ncbi_gene_type.gene_type_name, as: :result_gene_type_name
    indexes ncbi_result.ncbi_aliases.name, as: :result_aliases_name
    #indexes ncbi_result.ncbi_lineages.name, as: :result_lineages_name

    #indexes ncbi_result.genetic_markers.name, as: :result_genetic_markers_name #long index time!
    #indexes ncbi_result.ncbi_genomic_context.location, as: :result_genomic_context_location
    #indexes ncbi_result.ncbi_pubmed_articles.title, as: :result_pubmed_title #long index time!
    #indexes ncbi_result.ncbi_pubmed_articles.authors, as: :result_pubmed_authors
    #indexes ncbi_result.ncbi_pubmed_articles.abstract, as: :result_pubmed_abstract
    #indexes ncbi_result.ncbi_pubmed_articles.volume, as: :result_pubmed_volume
    #indexes ncbi_result.ncbi_pubmed_articles.year, as: :result_pubmed_year
    #indexes ncbi_result.ncbi_pubmed_articles.affiliations, as: :result_pubmed_affiliations

    indexes comments.name, as: :comments
    indexes incidents.name, as: :incidents

    set_property :delta => true

  end
  #  thinking_sphinx_scopes
  #sphinx_scope(:classified) {
  #
  #  where( "id IN (SELECT gene_id FROM ethnic_groupings) OR id IN (SELECT gene_id FROM curabilitizations) OR id IN (SELECT gene_id FROM age_onsetizations) OR id IN (SELECT gene_id FROM gender_classifications) OR id IN (SELECT gene_id FROM zygosity_classifications) OR id IN (SELECT gene_id FROM chromosome_classifications) OR id IN (SELECT gene_id FROM dominance_classifications)")
  #
  #  }


  private
  def self.calculate_progress(unclassified, classified)
    if unclassified > 0 || classified > 0
      all = unclassified.to_i + classified.to_i
      u = (100.to_f / all.to_f * unclassified).to_i
      c = 100 - u
      progress = { 'classified' => "#{c}", 'unclassified' => "#{u}"}
    else
      progress = { 'classified' => 0, 'unclassified' => 100}
    end
    return progress
  end

  def self.generate_related_link(type,id)
    if type == "HGNC"
      return "http://www.genenames.org/data/hgnc_data.php?hgnc_id=#{id}"
    elsif type == "Ensembl"
      return "http://www.ensembl.org/id/#{id}"
    elsif type == "HPRD"
      return "http://www.hprd.org/protein/#{id}"
    elsif type == "MIM"
      return "http://www.ncbi.nlm.nih.gov/omim/#{id}"
    elsif type == "Vega"
      return "http://vega.sanger.ac.uk/id/#{id}"
    end
  end

end

app/controllers/genes_controller.rb
class GenesController < ApplicationController

  before_filter :authenticate_user!
  authorize_resource
  # GET /genes
  # GET /genes.json

  require 'csv'

  def report
    @genes = Gene.where( common_in_sa: true )
  end

  def index
    if params[:search].present?
      #if params[:tag]
      #  @genes = Gene.tagged_with(params[:tag]).search(params[:search], page: params[:page], per_page: 20)
      #else
        @genes = Gene.includes(:ncbi_result,:incidents,:comments).search(params[:search], page: params[:page], per_page: 20)
      #end
    else
      if params[:filter]
        if params[:filter] == "common_in_sa"
          @genes = Gene.includes(:ncbi_result,:incidents,:comments).common_in_sa.order("name ASC").paginate(:page => params[:page], :per_page => 20)
        elsif params[:filter] == "classified"
          @genes = Gene.includes(:ncbi_result).with_classification.order("name ASC").paginate(:page => params[:page], :per_page => 20)
        elsif params[:filter] == "unclassified"
          @genes = Gene.includes(:ncbi_result,:incidents,:comments).without_classification.order("name ASC").paginate(:page => params[:page], :per_page => 20)
        end
      else
        @genes = Gene.includes(:ncbi_result,:incidents,:comments).order("name ASC").paginate(:page => params[:page], :per_page => 20)
      end
    end

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @genes }
    end
  end

  # GET /genes/1
  # GET /genes/1.json
  def show
    @gene = Gene.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gene }
    end
  end

  # GET /genes/new
  # GET /genes/new.json
  def new
    if current_user.role.name == "admin" || current_user.role.name == "staff"
      @gene = Gene.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @gene }
      end
    else
      respond_to do |format|
        format.html {redirect_to genes_path, notice: "You are not authorized to create new records."}
        format.json { render json: @gene }
      end
    end
  end

  # GET /genes/1/edit
  def edit
    @gene = Gene.find(params[:id])
    @ethnic_groups = EthnicGroup.order("value asc")
    @curabilities = Curability.order("value asc")
    @age_of_onsets = AgeOfOnset.all
    @causalities = Causality.all
    @genders = Gender.order("name ASC")
    @zygosities = Zygosity.all
    @chromosomes = Chromosome.all
    @dominances = Dominance.all
  end

  # POST /genes
  # POST /genes.json
  def create
    # read input file as CSV
    input_file = CSV.read(params[:gene][:mutation_annotation_file].tempfile.path, :headers => true, :col_sep => ";")
    input_file.each do |line|
      if current_user.role.name == "admin"
        @gene = Gene.create!(:name => line['Name'], :chromosome => line['Chromosome'], :number_amplicons => line['Num_Amplicons'], :total_bases => line['Total_Bases'], :covered_bases => line['Covered_Bases'], :overall_coverage => line['Overall_Coverage'])
      end

    end
    gene_ids_hash = {}                          # instantiate an empty hash to hold id's of gene w/o a ncbi_result
    Gene.all.each_with_index do |gene,index|    # loop over all genes
      unless gene.ncbi_result.present?
        gene_ids_hash[index] = gene.id          # save gene ids of gene w/o ncbi_result into hash for ncbi query
      end
    end
    #NcbiWorker.perform_async(gene_ids_hash)     # call sidekiq worker to create ncbi_result record
    if current_user.role.name == "admin"
      Resque.enqueue(NcbiScraper, gene_ids_hash)   # enqueue the hash of ids to the resque worker
    end


    respond_to do |format|
      if current_user.role.name == "admin" && @gene.save
        format.html { redirect_to genes_path, notice: 'Genes were successfully created. Additional information is being gathered...' }
        format.json { render json: @gene, status: :created, location: @gene }
      else
        format.html { render action: "new" }
        format.json { render json: @gene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genes/1
  # PUT /genes/1.json
  def update
    @gene = Gene.find(params[:id])
    @ethnic_groups = EthnicGroup.order("value asc")
    @curabilities = Curability.order("value asc")
    @age_of_onsets = AgeOfOnset.all
    @causalities = Causality.all
    @genders = Gender.order("name ASC")
    @zygosities = Zygosity.all
    @chromosomes = Chromosome.all
    @dominances = Dominance.all
    respond_to do |format|
      if current_user.role.name == "admin" || current_user.role.name == "staff"
        @gene.update_attributes(params[:gene])
        current_user.tag(@gene, with: "#{params[:gene][:comment_tags]}", on: :comments)
        current_user.tag(@gene, with: "#{params[:gene][:incident_tags]}", on: :incidents)
        format.html { redirect_to @gene, notice: 'Gene was successfully updated.' }
        format.json { head :no_content }
      else
        @ethnic_groups = EthnicGroup.order("value asc")
        @curabilities = Curability.order("value asc")
        @age_of_onsets = AgeOfOnset.all
        @causalities = Causality.all
        @genders = Gender.order("name ASC")
        @zygosities = Zygosity.all
        @chromosomes = Chromosome.all
        @dominances = Dominance.all
        format.html { render action: "show", error: "You are not authorized to edit this record." }
        format.json { render json: @gene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genes/1
  # DELETE /genes/1.json
  def destroy
    @gene = Gene.find(params[:id])
    if current_user.role.name == "admin"
      @gene.destroy
    end


    respond_to do |format|
      format.html { redirect_to genes_url }
      format.json { head :no_content }
    end
  end

  protected


end

app/helpers/genes_helper.rb
module GenesHelper

  def show_author(article)
    authors = article.authors.split(",")
    if authors.count == 1
      return authors[0].gsub("---\n- ","")
    elsif authors.count == 2
      return "#{authors[0].gsub("---\n- ","")} and #{authors[1].gsub("--- - ","")}"
    else
      return "#{authors[0].gsub("---\n- ","")} et al."
    end
  end

  def generate_related_link(link)
    if link.related_link_type == "HGNC"
      return "http://www.genenames.org/data/hgnc_data.php?hgnc_id=#{link.related_link_id}"
    elsif link.related_link_type == "Ensembl"
      return "http://www.ensembl.org/id/#{link.related_link_id}"
    elsif link.related_link_type == "HPRD"
      return "http://www.hprd.org/protein/#{link.related_link_id}"
    elsif link.related_link_type == "MIM"
      return "http://www.ncbi.nlm.nih.gov/omim/#{link.related_link_id}"
    elsif link.related_link_type == "Vega"
      return "http://vega.sanger.ac.uk/id/#{link.related_link_id}"
    end
  end

  def classified_gene(gene,i)
    if gene.ethnic_groups.size > 0 || gene.curabilities.size > 0 || gene.age_of_onsets.size > 0  || gene.causalities.size > 0 || gene.incidents.present? || gene.comments.present? || gene.genders.size > 0 || gene.zygosities.size > 0 || gene.chromosomes.size > 0 || gene.dominances.size > 0
      if i == 1
        image_tag('true.png')
      else
        return true
      end
    else
      if i == 1
        image_tag('false.png')
      else
        return false
      end
    end
  end

end

app/views/genes/_form.html.haml
= form_for @gene, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :mutation_annotation_file, :class => 'control-label'
    .controls
      = f.file_field :mutation_annotation_file, :class => 'file_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      genes_path, :class => 'btn'                                  |

app/views/genes/edit.html.haml
- model_class = Gene
- content_for :gene_title do
  = @gene.name
.page-header
  %h1= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, |
      :default => "Edit #{model_class.model_name.human} #{@gene.name}")                        |
-if can? :update, Gene
  = render :partial => 'update_form'

app/views/genes/index.html.haml
- model_class = Gene
- content_for :gene_title do
  = "Page - #{params[:page] || 1}"
.page-header
  %h1
    -unless params[:search].present?
      = t '.title', :default => model_class.model_name.human.pluralize
    -else
      = "Search Results for '#{params[:search]}'"

-if @genes.size > 0
  .well.well-small
    %h4
      Filters
    %p.filter_links
      = link_to image_tag('South-Africa-Flag.png', class: 'flag_t'), genes_path(:filter => 'common_in_sa')
      |
      = link_to 'classified', genes_path(:filter => 'classified')
      |
      = link_to 'unclassified', genes_path(:filter => 'unclassified')

  -if params[:search].present? || params[:filter].present?
    %p.result_size
      Found
      =pluralize(@genes.total_entries, 'gene')

  %p
    = will_paginate @genes, :class => 'apple_pagination'
  %table.table.table-striped
    %thead
      %tr
        %th.left= model_class.human_attribute_name(:name)
        %th.left Full Name
        %th.left= "IT Phenotype"
        %th.left= "NCBI Phenotype"
        //%th.left= "Also known as"
        %th Common
        %th Coverage
        %th Classified
        - if can? :update, Gene
          %th= t '.actions', :default => t("helpers.actions")
    %tbody
      - @genes.each do |gene|
        %tr
          %td.left= link_to gene.name, gene_path(gene)
          %td.left.narrow= gene.ncbi_result.official_full_name.titleize || "not set"
          %td.left.narrow= gene.disease || "not set"
          %td.left.narrow= gene.ncbi_result.phenotype || "not set"
          %td=raw gene.common_in_sa ? image_tag('South-Africa-Flag.png', class: 'flag'): "<span class='red'>no</span>"
          %td= gene.overall_coverage || "not set"
          %td= classified_gene(gene,1)
          -#- if staff? || admin?
          -if can? :update, Gene
            %td
              = link_to t('.edit', :default => t("helpers.links.edit")),
                edit_gene_path(gene), :class => 'btn btn-mini'
              -if can? :destroy, Gene
                = link_to t('.destroy', :default => t("helpers.links.destroy")),
                  gene_path(gene),
                  :method => :delete,
                  :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                  :class => 'btn btn-mini btn-danger'
  %p
    = will_paginate @genes, :class => 'apple_pagination'

-else
  %p
    No genes match your query.
-if can? :create, Gene
  = link_to t('.new', :default => t("helpers.links.new")), new_gene_path, :class => 'btn btn-primary'

app/views/genes/new.html.haml
- model_class = Gene
- content_for :gene_title do
  = @gene.name
.page-header
  %h1= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, |
      :default => "New #{model_class.model_name.human}")                                      |
-if can? :create, Gene
  = render :partial => 'form'

app/views/genes/report.html.haml
- model_class = Gene
- content_for :gene_title do
  = "Page - #{params[:page] || 1}"
.page-header
  %h1
    -unless params[:search].present?
      = t '.title', :default => model_class.model_name.human.pluralize
    -else
      = "Search Results for '#{params[:search]}'"

-if @genes.size > 0
  .well.well-small
    %h4
      Filters
    %p.filter_links
      = link_to image_tag('South-Africa-Flag.png', class: 'flag_t'), genes_path(:filter => 'common_in_sa')
      |
      = link_to 'classified', genes_path(:filter => 'classified')
      |
      = link_to 'unclassified', genes_path(:filter => 'unclassified')

  -if params[:search].present? || params[:filter].present?
    %p.result_size
      Found
      =pluralize(@genes.total_entries, 'gene')

  %table.table.table-striped
    %thead
      %tr
        %th.left= model_class.human_attribute_name(:name)
        %th.left Full Name
        %th.left= "NCBI Phenotype"
        %th Common
        %th Onset
        %th Causality
        %th Outcome
        - if can? :update, Gene
          %th= t '.actions', :default => t("helpers.actions")
    %tbody
      - @genes.each do |gene|
        %tr
          %td.left= link_to gene.name, gene_path(gene)
          %td.left.narrow= gene.ncbi_result.official_full_name.titleize || "not set"
          %td.left.narrow= gene.ncbi_result.phenotype || "not set"
          %td=raw gene.common_in_sa ? image_tag('South-Africa-Flag.png', class: 'flag'): "<span class='red'>no</span>"
          %td= gene.age_of_onsets.map(&:value).join(", ") || "not set"
          %td= gene.causalities.map(&:name).join(", ") || "not set"
          %td= gene.curabilities.map(&:value).join(", ") || "not set"
          %td= gene.incidents.collect { |incident| "#{incident}"}.join(" ") || "not set"
          -#- if staff? || admin?
          -if can? :update, Gene
            %td
              = link_to t('.edit', :default => t("helpers.links.edit")),
                edit_gene_path(gene), :class => 'btn btn-mini'
              -if can? :destroy, Gene
                = link_to t('.destroy', :default => t("helpers.links.destroy")),
                  gene_path(gene),
                  :method => :delete,
                  :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                  :class => 'btn btn-mini btn-danger'

-else
  %p
    No genes match your query.
-if can? :create, Gene
  = link_to t('.new', :default => t("helpers.links.new")), new_gene_path, :class => 'btn btn-primary'

app/views/genes/show.html.haml
- model_class = Gene
- content_for :gene_title do
  = " - Details on #{@gene.name}"
.page-header
  %h1
    Details for Gene
    =@gene.name
    = image_tag('South-Africa-Flag_32.png', class: "flag_m") if @gene.common_in_sa?
.well
  %legend
    %i.icon-briefcase
    Ion Torrent
  %table.table.table-striped
    %thead
      %tr
        %th
          =model_class.human_attribute_name(:name)
        %th
          =model_class.human_attribute_name(:chromosome)
        %th
          =model_class.human_attribute_name(:disease)
        %th
          =model_class.human_attribute_name(:number_amplicons)
        %th
          =model_class.human_attribute_name(:total_bases)
        %th
          =model_class.human_attribute_name(:covered_bases)
        %th
          =model_class.human_attribute_name(:overall_coverage)
    %tbody
      %tr
        %td
          =@gene.name
        %td
          =@gene.chromosome
        %td
          =@gene.disease
        %td
          =@gene.number_amplicons
        %td
          =@gene.total_bases
        %td
          =@gene.covered_bases
        %td
          =@gene.overall_coverage
  .clear


.well
  %legend
    %i.icon-tags
    Classification
  -unless classified_gene(@gene,nil)
    %p
      This gene has not yet been classified.
  %dl.dl-horizontal
    %dt
      Common in SA:
    %dd
      =raw @gene.common_in_sa ? "<span class='green'>yes</span>":"<span class='red'>no</span>"
    -if @gene.causalities.size > 0
      %dt
        Causality:
      %dd
        = @gene.causalities.map(&:name).join(", ")
    -if @gene.ethnic_groups.size > 0
      %dt
        Ethnic Groups:
      %dd
        = @gene.ethnic_groups.map(&:value).join(", ")

    -if @gene.curabilities.size > 0
      %dt
        Outcome:

      %dd
        = @gene.curabilities.map(&:value).join(", ")

    -if @gene.age_of_onsets.size > 0
      %dt
        Age of Onset:
      %dd
        = @gene.age_of_onsets.map(&:value).join(", ")

    -if @gene.genders.size > 0
      %dt
        Gender:
      %dd
        = @gene.genders.map(&:name).join(", ")

    -if @gene.zygosities.size > 0
      %dt
        Zygosity:
      %dd
        = @gene.zygosities.map(&:name).join(", ")

    -if @gene.chromosomes.size > 0
      %dt
        Chromosomes:
      %dd
        = @gene.chromosomes.map(&:name).join(", ")

    -if @gene.dominances.size > 0
      %dt
        Dominance:
      %dd
        = @gene.dominances.map(&:name).join(", ")

    -if @gene.comments.present?
      %dt.tag
        Comment Tags:
      %dd.tag.left
        =raw @gene.comments.collect { |comment| "<span class='badge badge-important'>#{comment}</span>"}.join(" ")

    -if @gene.incidents.present?
      %dt.tag
        Incident Tags:
      %dd.tag.left
        =raw @gene.incidents.collect { |incident| "<span class='badge badge-important'>#{incident}</span>"}.join(" ")


  -if can? :update, Gene
    = link_to "edit", edit_gene_path(@gene), class: "pull-right"
-if @gene.ncbi_result.present?
  .well
    %legend
      %i.icon-book
      Summary
    %dl.dl-horizontal
      %dt
        Official Symbol
      %dd
        =@gene.ncbi_result.official_symbol
      %dt
        Official Full Name
      %dd
        =@gene.ncbi_result.official_full_name.titleize
      %dt
        Gene ID
      %dd
        =link_to @gene.ncbi_result.ncbi_gene_id, "http://www.ncbi.nlm.nih.gov/gene/#{@gene.ncbi_result.ncbi_gene_id}", target: "_blank"
      %dt
        Primary source
      %dd
        =link_to "#{@gene.ncbi_result.ncbi_related_links.first.related_link_type}:#{@gene.ncbi_result.ncbi_related_links.first.related_link_id}", generate_related_link(@gene.ncbi_result.ncbi_related_links.first), target: "_blank"
      %dt
        Related links
      %dd
        -@gene.ncbi_result.ncbi_related_links[1..-1].each do |rl|
          = link_to "#{rl.related_link_type}:#{rl.related_link_id}", generate_related_link(rl), target: "_blank"
          =" | "
      %dt
        Gene type
      %dd
        =@gene.ncbi_result.ncbi_gene_type.gene_type_name
      %dt
        RefSeq status
      %dd
        =@gene.ncbi_result.refseq_status || "none"
      %dt
        Organism
      %dd
        Homo sapiens (human)
      -if @gene.ncbi_result.ncbi_lineages.present?
        %dt
          Lineage
        %dd
          =@gene.ncbi_result.ncbi_lineages.map(&:name).join("; ")
      -if @gene.ncbi_result.ncbi_aliases.present?
        %dt
          Also known as
        %dd
          =@gene.ncbi_result.ncbi_aliases.map(&:name).join(", ")
      %dt
        Phenotype
      %dd
        =@gene.ncbi_result.phenotype
      %dt
        Summary
      %dd
        =@gene.ncbi_result.summary
    .clear

  -if @gene.ncbi_result.ncbi_pubmed_articles.length > 0
    .well
      %legend
        %i.icon-bookmark
        Related articles in PubMed
      %ol
        -@gene.ncbi_result.ncbi_pubmed_articles.order("year DESC").limit(10).each do |article|
          %li
            = link_to article.title.to_blurb(), "http://www.ncbi.nlm.nih.gov/pubmed/#{article.pubmed}", target: "_blank"
            = " "
            %i
              = show_author(article)+","
            = article.journal+","
            %strong
              = article.year+","
            = article.volume+","
            = article.pages
      %p
        %i.icon-list
        =link_to "See all publications", ncbi_pubmed_article_path(@gene.id)
        =@gene.ncbi_result.ncbi_pubmed_articles.size
    .clear
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    genes_path, :class => 'btn'                              |
  -if can? :update, Gene
    = link_to t('.edit', :default => t("helpers.links.edit")),edit_gene_path(@gene), :class => 'btn'
  -if can? :destroy, Gene
    = link_to t('.destroy', :default => t("helpers.links.destroy")),
      gene_path(@gene),
      :method => 'delete',
      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
      :class => 'btn btn-danger'